#!/usr/bin/env python3
"""
Standalone script to generate test reports from existing test results or run tests and generate reports.
"""
import sys
import subprocess
import json
from pathlib import Path
from datetime import datetime

# Add tests directory to path
sys.path.insert(0, str(Path(__file__).parent / "tests"))

from test_report_generator import TestReportGenerator


def main():
    """Generate test reports."""
    print("=" * 80)
    print("Backend Test Report Generator")
    print("=" * 80)
    print()
    
    # Check if backend is running
    try:
        import requests
        response = requests.get("http://localhost:8000/health", timeout=2)
        if response.status_code == 200:
            print("✓ Backend is running")
        else:
            print("⚠ Backend health check failed")
    except:
        print("⚠ Cannot connect to backend (tests may skip)")
    
    print()
    print("Running tests and collecting metrics...")
    print()
    
    # Run pytest with custom reporting
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-v", "--tb=short"],
        cwd=Path(__file__).parent,
        capture_output=False
    )
    
    print()
    print("=" * 80)
    print("Generating Reports...")
    print("=" * 80)
    print()
    
    # Note: Reports are generated by pytest hooks in conftest_report.py
    # This script just runs the tests
    
    reports_dir = Path(__file__).parent / "test_reports"
    if reports_dir.exists():
        json_reports = list(reports_dir.glob("test_report_*.json"))
        html_reports = list(reports_dir.glob("test_report_*.html"))
        
        if json_reports:
            latest_json = max(json_reports, key=lambda p: p.stat().st_mtime)
            print(f"✓ Latest JSON report: {latest_json}")
        
        if html_reports:
            latest_html = max(html_reports, key=lambda p: p.stat().st_mtime)
            print(f"✓ Latest HTML report: {latest_html}")
            print()
            print(f"📊 Open in browser: file://{latest_html.absolute()}")
    
    print()
    print("=" * 80)
    
    return result.returncode


if __name__ == "__main__":
    sys.exit(main())

